# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './fingerPrint/fingerPrint_kyumin/qt-designer/ammend_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# 페이지는 4개 존재하며 각각의 페이지 내부의 요소들은 이름의 앞에 통일된 글자를 추가
# fingerPrint(출석): fp
# outing(외출): out
# new_fingerPrint(지문 등록): new
# delete_fingerPrint(지문 삭제): delete


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 480)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fingerprint_button = QtWidgets.QPushButton(self.centralwidget)
        self.fingerprint_button.setGeometry(QtCore.QRect(40, 40, 120, 95))
        self.fingerprint_button.setStyleSheet("background-color: rgb(78, 78, 78);\n"
"color: rgb(227, 227, 227); border: 0px;")
        self.fingerprint_button.setObjectName("fingerprint_button")
        self.fingerprint_button.clicked.connect(lambda: self.changePage(0))
        self.outing_button = QtWidgets.QPushButton(self.centralwidget)
        self.outing_button.setGeometry(QtCore.QRect(40, 140, 120, 95))
        self.outing_button.setStyleSheet("background-color: rgb(78, 78, 78);\n"
"color: rgb(227, 227, 227); border: 0px;")
        self.outing_button.setObjectName("outing_button")
        self.outing_button.clicked.connect(lambda: self.changePage(1))
        self.new_fingerprint_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_fingerprint_button.setGeometry(QtCore.QRect(40, 240, 120, 95))
        self.new_fingerprint_button.setStyleSheet("background-color: rgb(78, 78, 78);\n"
"color: rgb(227, 227, 227); border: 0px;")
        self.new_fingerprint_button.setObjectName("new_fingerprint_button")
        self.new_fingerprint_button.clicked.connect(lambda: self.changePage(2))
        self.delete_fingerprint_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_fingerprint_button.setGeometry(QtCore.QRect(40, 340, 120, 95))
        self.delete_fingerprint_button.setStyleSheet("background-color: rgb(78, 78, 78);\n"
"color: rgb(227, 227, 227); border: 0px;")
        self.delete_fingerprint_button.setObjectName("delete_fingerprint_button")
        self.delete_fingerprint_button.clicked.connect(lambda: self.changePage(3))
        self.pages = QtWidgets.QStackedWidget(self.centralwidget)
        self.pages.setGeometry(QtCore.QRect(180, 40, 611, 391))
        self.pages.setAutoFillBackground(False)
        self.pages.setObjectName("pages")
        self.fingerprint_page = QtWidgets.QWidget()
        self.fingerprint_page.setObjectName("fingerprint_page")
        self.fp_label_date = QtWidgets.QLabel(self.fingerprint_page)
        self.fp_label_date.setGeometry(QtCore.QRect(40, 0, 521, 101))
        self.fp_label_date.setAutoFillBackground(False)
        self.fp_label_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 35px;")
        self.fp_label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.fp_label_date.setObjectName("fp_label_date")
        self.fp_label_now = QtWidgets.QLabel(self.fingerprint_page)
        self.fp_label_now.setGeometry(QtCore.QRect(350, 135, 211, 121))
        self.fp_label_now.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 20px;")
        self.fp_label_now.setAlignment(QtCore.Qt.AlignCenter)
        self.fp_label_now.setObjectName("fp_label_now")
        self.fp_label_text = QtWidgets.QLabel(self.fingerprint_page)
        self.fp_label_text.setGeometry(QtCore.QRect(40, 290, 521, 101))
        self.fp_label_text.setAutoFillBackground(False)
        self.fp_label_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 25px;")
        self.fp_label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.fp_label_text.setObjectName("fp_label_text")
        self.fp_pushButton_on = QtWidgets.QPushButton(self.fingerprint_page)
        self.fp_pushButton_on.setGeometry(QtCore.QRect(50, 135, 121, 121))
        self.fp_pushButton_on.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.fp_pushButton_on.setObjectName("fp_pushButton_on")
        self.fp_pushButton_out = QtWidgets.QPushButton(self.fingerprint_page)
        self.fp_pushButton_out.setGeometry(QtCore.QRect(175, 135, 121, 121))
        self.fp_pushButton_out.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.fp_pushButton_out.setObjectName("fp_pushButton_out")
        self.pages.addWidget(self.fingerprint_page)
        self.outing_page = QtWidgets.QWidget()
        self.outing_page.setObjectName("outing_page")
        self.out_label_date = QtWidgets.QLabel(self.outing_page)
        self.out_label_date.setGeometry(QtCore.QRect(40, 0, 521, 101))
        self.out_label_date.setAutoFillBackground(False)
        self.out_label_date.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 35px;")
        self.out_label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.out_label_date.setObjectName("out_label_date")
        self.out_label_now = QtWidgets.QLabel(self.outing_page)
        self.out_label_now.setGeometry(QtCore.QRect(350, 135, 211, 121))
        self.out_label_now.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 20px;")
        self.out_label_now.setAlignment(QtCore.Qt.AlignCenter)
        self.out_label_now.setObjectName("out_label_now")
        self.out_label_text = QtWidgets.QLabel(self.outing_page)
        self.out_label_text.setGeometry(QtCore.QRect(40, 290, 521, 101))
        self.out_label_text.setAutoFillBackground(False)
        self.out_label_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 25px;")
        self.out_label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.out_label_text.setObjectName("out_label_text")
        self.out_pushButton_gohan = QtWidgets.QPushButton(self.outing_page)
        self.out_pushButton_gohan.setGeometry(QtCore.QRect(50, 135, 121, 57))
        self.out_pushButton_gohan.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.out_pushButton_gohan.setObjectName("out_pushButton_gohan")
        self.out_pushButton_lib = QtWidgets.QPushButton(self.outing_page)
        self.out_pushButton_lib.setGeometry(QtCore.QRect(175, 135, 121, 57))
        self.out_pushButton_lib.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.out_pushButton_lib.setObjectName("out_pushButton_lib")
        self.out_pushButton_walk = QtWidgets.QPushButton(self.outing_page)
        self.out_pushButton_walk.setGeometry(QtCore.QRect(50, 200, 121, 57))
        self.out_pushButton_walk.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.out_pushButton_walk.setObjectName("out_pushButton_walk")
        self.out_pushButton_else = QtWidgets.QPushButton(self.outing_page)
        self.out_pushButton_else.setGeometry(QtCore.QRect(175, 200, 121, 57))
        self.out_pushButton_else.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.out_pushButton_else.setObjectName("out_pushButton_else")
        self.pages.addWidget(self.outing_page)
        self.new_fingerprint_page = QtWidgets.QWidget()
        self.new_fingerprint_page.setObjectName("new_fingerprint_page")
        self.new_pushButton_1 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_1.setGeometry(QtCore.QRect(10, 180, 100, 100))
        self.new_pushButton_1.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_1.setObjectName("new_pushButton_1")
        self.new_pushButton_2 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_2.setGeometry(QtCore.QRect(110, 180, 100, 100))
        self.new_pushButton_2.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_2.setObjectName("new_pushButton_2")
        self.new_pushButton_3 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_3.setGeometry(QtCore.QRect(210, 180, 100, 100))
        self.new_pushButton_3.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_3.setObjectName("new_pushButton_3")
        self.new_pushButton_4 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_4.setGeometry(QtCore.QRect(310, 180, 100, 100))
        self.new_pushButton_4.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_4.setObjectName("new_pushButton_4")
        self.new_pushButton_5 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_5.setGeometry(QtCore.QRect(410, 180, 100, 100))
        self.new_pushButton_5.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_5.setObjectName("new_pushButton_5")
        self.new_pushButton_back = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_back.setGeometry(QtCore.QRect(510, 180, 100, 100))
        self.new_pushButton_back.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_back.setObjectName("new_pushButton_back")
        self.new_pushButton_6 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_6.setGeometry(QtCore.QRect(10, 290, 100, 100))
        self.new_pushButton_6.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_6.setObjectName("new_pushButton_6")
        self.new_pushButton_7 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_7.setGeometry(QtCore.QRect(110, 290, 100, 100))
        self.new_pushButton_7.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_7.setObjectName("new_pushButton_7")
        self.new_pushButton_8 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_8.setGeometry(QtCore.QRect(210, 290, 100, 100))
        self.new_pushButton_8.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_8.setObjectName("new_pushButton_8")
        self.new_pushButton_9 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_9.setGeometry(QtCore.QRect(310, 290, 100, 100))
        self.new_pushButton_9.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_9.setObjectName("new_pushButton_9")
        self.new_pushButton_0 = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_0.setGeometry(QtCore.QRect(410, 290, 100, 100))
        self.new_pushButton_0.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_0.setObjectName("new_pushButton_0")
        self.new_pushButton_ok = QtWidgets.QPushButton(self.new_fingerprint_page)
        self.new_pushButton_ok.setGeometry(QtCore.QRect(510, 290, 100, 100))
        self.new_pushButton_ok.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.new_pushButton_ok.setObjectName("new_pushButton_ok")
        self.new_label_text = QtWidgets.QLabel(self.new_fingerprint_page)
        self.new_label_text.setGeometry(QtCore.QRect(40, 0, 521, 160))
        self.new_label_text.setAutoFillBackground(False)
        self.new_label_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 35px;")
        self.new_label_text.setAlignment(QtCore.Qt.AlignCenter)
        self.new_label_text.setObjectName("new_label_text")
        self.pages.addWidget(self.new_fingerprint_page)
        self.delete_fingerprint_page = QtWidgets.QWidget()
        self.delete_fingerprint_page.setObjectName("delete_fingerprint_page")
        self.delete_pushButton_1 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_1.setGeometry(QtCore.QRect(10, 180, 100, 100))
        self.delete_pushButton_1.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_1.setObjectName("delete_pushButton_1")
        self.delete_pushButton_2 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_2.setGeometry(QtCore.QRect(110, 180, 100, 100))
        self.delete_pushButton_2.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_2.setObjectName("delete_pushButton_2")
        self.delete_pushButton_3 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_3.setGeometry(QtCore.QRect(210, 180, 100, 100))
        self.delete_pushButton_3.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_3.setObjectName("delete_pushButton_3")
        self.delete_pushButton_4 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_4.setGeometry(QtCore.QRect(310, 180, 100, 100))
        self.delete_pushButton_4.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_4.setObjectName("delete_pushButton_4")
        self.delete_pushButton_5 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_5.setGeometry(QtCore.QRect(410, 180, 100, 100))
        self.delete_pushButton_5.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_5.setObjectName("delete_pushButton_5")
        self.delete_pushButton_back = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_back.setGeometry(QtCore.QRect(510, 180, 100, 100))
        self.delete_pushButton_back.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_back.setObjectName("delete_pushButton_back")
        self.delete_pushButton_6 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_6.setGeometry(QtCore.QRect(10, 290, 100, 100))
        self.delete_pushButton_6.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_6.setObjectName("delete_pushButton_6")
        self.delete_pushButton_7 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_7.setGeometry(QtCore.QRect(110, 290, 100, 100))
        self.delete_pushButton_7.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_7.setObjectName("delete_pushButton_7")
        self.delete_pushButton_8 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_8.setGeometry(QtCore.QRect(210, 290, 100, 100))
        self.delete_pushButton_8.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_8.setObjectName("delete_pushButton_8")
        self.delete_pushButton_9 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_9.setGeometry(QtCore.QRect(310, 290, 100, 100))
        self.delete_pushButton_9.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_9.setObjectName("delete_pushButton_9")
        self.delete_pushButton_0 = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_0.setGeometry(QtCore.QRect(410, 290, 100, 100))
        self.delete_pushButton_0.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_0.setObjectName("delete_pushButton_0")
        self.delete_pushButton_ok = QtWidgets.QPushButton(self.delete_fingerprint_page)
        self.delete_pushButton_ok.setGeometry(QtCore.QRect(510, 290, 100, 100))
        self.delete_pushButton_ok.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"color: rgb(227, 227, 227); border: 0.5px solid rgb(70, 70, 70);")
        self.delete_pushButton_ok.setObjectName("delete_pushButton_ok")
        self.delete_pushButton_text = QtWidgets.QLabel(self.delete_fingerprint_page)
        self.delete_pushButton_text.setGeometry(QtCore.QRect(40, 0, 521, 160))
        self.delete_pushButton_text.setAutoFillBackground(False)
        self.delete_pushButton_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(30, 30, 30);   \n"
"border: 1px solid rgb(70, 70, 70);\n"
"font-size: 35px;")
        self.delete_pushButton_text.setAlignment(QtCore.Qt.AlignCenter)
        self.delete_pushButton_text.setObjectName("delete_pushButton_text")
        self.pages.addWidget(self.delete_fingerprint_page)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # 세팅 완료 후 자동으로 출석 페이지 클릭
        self.fingerprint_button.click()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fingerprint_button.setText(_translate("MainWindow", "출석"))
        self.outing_button.setText(_translate("MainWindow", "외출"))
        self.new_fingerprint_button.setText(_translate("MainWindow", "지문 등록"))
        self.delete_fingerprint_button.setText(_translate("MainWindow", "지문 삭제"))
        self.fp_label_date.setText(_translate("MainWindow", "YYYY.mm.dd 오전 HH:MM:SS"))
        self.fp_label_now.setText(_translate("MainWindow", "현재 재실: 00명"))
        self.fp_label_text.setText(_translate("MainWindow", "지문을 인식해 주세요"))
        self.fp_pushButton_on.setText(_translate("MainWindow", "등교"))
        self.fp_pushButton_out.setText(_translate("MainWindow", "하교"))
        self.out_label_date.setText(_translate("MainWindow", "YYYY.mm.dd 오전 HH:MM:SS"))
        self.out_label_now.setText(_translate("MainWindow", "현재 재실: 00명"))
        self.out_label_text.setText(_translate("MainWindow", "지문을 인식해 주세요"))
        self.out_pushButton_gohan.setText(_translate("MainWindow", "식사"))
        self.out_pushButton_lib.setText(_translate("MainWindow", "도서관"))
        self.out_pushButton_walk.setText(_translate("MainWindow", "산책"))
        self.out_pushButton_else.setText(_translate("MainWindow", "기타"))
        self.new_pushButton_1.setText(_translate("MainWindow", "1"))
        self.new_pushButton_2.setText(_translate("MainWindow", "2"))
        self.new_pushButton_3.setText(_translate("MainWindow", "3"))
        self.new_pushButton_4.setText(_translate("MainWindow", "4"))
        self.new_pushButton_5.setText(_translate("MainWindow", "5"))
        self.new_pushButton_back.setText(_translate("MainWindow", "<-"))
        self.new_pushButton_6.setText(_translate("MainWindow", "6"))
        self.new_pushButton_7.setText(_translate("MainWindow", "7"))
        self.new_pushButton_8.setText(_translate("MainWindow", "8"))
        self.new_pushButton_9.setText(_translate("MainWindow", "9"))
        self.new_pushButton_0.setText(_translate("MainWindow", "0"))
        self.new_pushButton_ok.setText(_translate("MainWindow", "확인"))
        self.new_label_text.setText(_translate("MainWindow", "학번을 입력해주세요\n"
"\n"
"2423002"))
        self.delete_pushButton_1.setText(_translate("MainWindow", "1"))
        self.delete_pushButton_2.setText(_translate("MainWindow", "2"))
        self.delete_pushButton_3.setText(_translate("MainWindow", "3"))
        self.delete_pushButton_4.setText(_translate("MainWindow", "4"))
        self.delete_pushButton_5.setText(_translate("MainWindow", "5"))
        self.delete_pushButton_back.setText(_translate("MainWindow", "<-"))
        self.delete_pushButton_6.setText(_translate("MainWindow", "6"))
        self.delete_pushButton_7.setText(_translate("MainWindow", "7"))
        self.delete_pushButton_8.setText(_translate("MainWindow", "8"))
        self.delete_pushButton_9.setText(_translate("MainWindow", "9"))
        self.delete_pushButton_0.setText(_translate("MainWindow", "0"))
        self.delete_pushButton_ok.setText(_translate("MainWindow", "확인"))
        self.delete_pushButton_text.setText(_translate("MainWindow", "학번을 입력해주세요\n"
"\n" "2423002"))
            
    # 페이지 전환 함수
    def changePage(self, pageIndex):
         self.pages.setCurrentIndex(pageIndex)
         self.buttons = [self.fingerprint_button, self.outing_button, self.new_fingerprint_button, self.delete_fingerprint_button]
         for button in self.buttons:
            button.setStyleSheet("background-color: rgb(78, 78, 78); color: rgb(227, 227, 227); border: 0px;")
            self.buttons[pageIndex].setStyleSheet("background-color: gray; color: rgb(227, 227, 227); border: 0px;")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    sys.exit(app.exec_())
